#tomcat啓動端口,#服務器編號
server:
    id: 1
    port: 8080

#自定義的屬性，衹是測試
test:
    id: 110
    name: haha

#配置環境模式（dev開發環境，test測試環境，prod生產環境）
spring:
    profiles:
      active: test

#mybatis:
#  type-aliases-package: com.shuabao.core.mapper
#  mapper-locations: classpath:com/shuabao/core/mapper/*.xml


#配置mysql數據源，可以配置多個數據源
---
spring:
    profiles: dev
    commondatasource:
        url: jdbc:mysql://47.106.105.52:3306/test?useUnicode=true&amp;characterEncoding=utf-8&generateSimpleParameterMetadata=true&useSSL=false
        username: saer
        password: saer
        driver-class-name: com.mysql.jdbc.Driver
    upload:
        dir: F:\img\
#  otherDataSource:
#       url: jdbc:mysql://47.106.105.52:3306/test?useUnicode=true&amp;characterEncoding=utf-8&generateSimpleParameterMetadata=true
#       username: saer
#       password: saer
#       driver-class-name: com.mysql.jdbc.Driver
---
spring:
    profiles: test
    commondatasource:
        url: jdbc:mysql://47.106.105.52:3306/test?useUnicode=true&amp;characterEncoding=utf-8&generateSimpleParameterMetadata=true
        username: saer
        password: saer
        driver-class-name: com.mysql.jdbc.Driver
    upload:
        dir: /data/static/img/
---
spring:
    profiles: prod
    commondatasource:
        url: jdbc:mysql://47.106.105.52:3306/test?useUnicode=true&amp;characterEncoding=utf-8&generateSimpleParameterMetadata=true
        username: saer
        password: saer
        driver-class-name: com.mysql.jdbc.Driver
    upload:
        dir: /data/static/img/
---
spring:
    profiles: dev
    redis:
      common:
          host: 47.106.105.52
          port: 6379
          password: saer
---
spring:
    profiles: test
    redis:
      common:
          host: 47.106.105.52
          port: 6379
          password: saer
---
spring:
    profiles: prod
    redis:
      common:
          host: 47.106.105.52
          port: 6379
          password: saer
---
spring:
    profiles: dev
    zookeeper:
        host: 47.106.105.52:2181
---
spring:
    profiles: test
    zookeeper:
        host: 47.106.105.52:2181
---
spring:
    profiles: prod
    zookeeper:
        host: 47.106.105.52:2181